import "../styles/globals.css"
import { ThemeProvider } from "/context/ThemeContext"
import { Istok_Web } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"
import Head from "next/head"

const istok = Istok_Web({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-istok",
	display: "swap",
})

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Michele Moro - Personal website</title>
				<meta
					name="description"
					content="Personal website, generated by create next app and styled with tailwindcss"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0"
				></meta>
				<link rel="icon" href="/icon.ico" />
			</Head>
			<div className={istok.className}>
				<ThemeProvider>
					<Component {...pageProps} />
					<Analytics />
				</ThemeProvider>
			</div>
		</>
	)
}

export default MyApp
