import Head from "next/head"
import React, { useEffect, useRef } from "react"
import { Header } from "../components/Header"
import { Footer } from "../components/Footer"
import { EduAndWorkSection } from "../components/EduAndWorkSection"
import { ProjectsSection } from "../components/ProjectsSection"
import { InfoSection } from "../components/InfoSection"
import { WelcomeNaviSection } from "../components/welcome-navi-section/WelcomeNaviSection"
import { aboutStation, experienceStation } from "../constants"
import { useTheme } from "../context/ThemeContext"
import { StationsDirectionSign } from "../components/StationsDirectionSign"

export default function Home() {
	const { isDarkMode, setIsDarkMode } = useTheme()

	useEffect(() => {
		//defaults to dark/light mode from device
		const defaultDark = window.matchMedia(
			"(prefers-color-scheme: dark)"
		).matches

		setIsDarkMode(defaultDark)
	}, [setIsDarkMode])

	const ref1 = useRef(null)
	const ref2 = useRef(null)
	const ref3 = useRef(null)

	return (
		<>
			<Head>
				<title>Michele Moro - Personal website</title>
				<meta
					name="description"
					content="Personal website, generated by create next app and styled with tailwindcss"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0"
				></meta>
				<link rel="icon" href="/icon.ico" />
			</Head>
			<div className={isDarkMode ? "dark" : ""}>
				<div className="flex flex-col items-center break-words bg-neutral-100 dark:bg-neutral-900">
					<Header refs={[ref1, ref2, ref3]} />
					<main className="rounded-b-xl max-w-full text-slate-900 dark:text-slate-100  transition-colors duration-500 shadow-[0px_0px_10px_0px_#94a3b8] dark:shadow-sm">
						<WelcomeNaviSection />
						<EduAndWorkSection scrollRef={ref1} />
						<StationsDirectionSign downArr={[aboutStation]} />
						<ProjectsSection scrollRef={ref2} />
						<StationsDirectionSign upArr={[experienceStation]} />
						<InfoSection scrollRef={ref3} />
					</main>
					<Footer />
				</div>
			</div>
		</>
	)
}
